### ISSUE TITLE
Where to install on Linux with Tex-Live?

### ISSUE THREAD

**Issue by brettpim** [aaron-siegel/combgames#1]
On Tex-Live installation on Linux, where should I install combgames to?

I have tried putting  combgames in my $TEXINPUTS directory
I have tried putting  combgames/tex/latex/combgames folder in my $TEXINPUTS directory
I have tried putting the combgames folder in /usr/share/texlive/texmf-dist/tex/latex/
I have tried putting the combgames/tex/latex/combgames folder directly in /usr/share/texlive/texmf-dist/tex/latex/

**Comment by brettpim** [comment]
For installing in one's $HOME directory on a linux/unix system:
- Create a directory for local TeX files (on my system it is $HOME/Projects/TEXINPUTS/)
- In .bashrc set up a TEXINPUTS environment variable. The trailing *double* slash is *important* because it tells your TeX compiler to search all subdirectories recursively:
```
export TEXINPUTS=$TEXINPUTS:$HOME/Projects/TEXINPUTS//
```
- put `combgames` in $TEXINPUTS/

This procedure enables TeX to find the .sty and included .tex files but I have not figured out how to have TeX find the fonts yet.

**Comment by brettpim** [comment]
For fonts there is an excellent [guide to font installation on stack exchange](https://tex.stackexchange.com/questions/88423/manual-font-installation).  From that:
- run `kpsewhich --var-value=TEXMFLOCAL` to find your local TeX MF directory.  I will call the reported directory $TEXMFLOCAL even though there is not an environment variable with that name (at least not on my system)
- recursively copy combgames/fonts to $TEXMFLOACL/fonts.  This is not a simple as running `sudo cp -r combgames/fonts/ $TEXMFLOCAL/fonts/` because there may already be a `fonts` in `$TEXMFLOCAL/` or there may already be a `source` in `$TEXMFLOCAL/fonts/`.  The easiest method is probably `sudo rsync -r combgames/fonts/ $TEXMFLOCAL/fonts/`
- run `sudo texhash`

**Comment by aaron-siegel** [comment]
On MacOS, here is what I did to get combgames in the directory of my choice:

cd ~/Library/texmf/tex/latex
ln -s [mydir]/tex/latex/combgames combgames
cd ~/Library/texmf/fonts/source
ln -s [mydir]/fonts/source/cgames cgames

where [mydir] points to the root dir of the github repo clone.

(I realize MacOS is not unix/linux, but I'm putting this here in case someone finds this thread with a similar question)
